### PR TITLE
Allow updates with same value on ProgrammableSwitchEvent  #62

### PR DESCRIPTION
**Pull request by DaRe92**

### CODE REVIEW

**Review by justme-1968 — COMMENTED** [review]
thank you for your patch.

but i think this:

`!mapping.characteristic_type === 'ProgrammableSwitchEvent'`

should be:

`mapping.characteristic_type !== 'ProgrammableSwitchEvent'` 

in both instances. you don't want to negate a string but check for not equal.

**Comment by DaRe92** [comment]
i changed it

**Comment by justme-1968** [comment]
merged

**Comment by DragonWork** [comment]
> merged

This broke caching behavior for me. Every time HomeKit requests for the current state, the first ever cached value (after initial homebridge startup) is returned (despite being changed afterwards and being stale). Even when changing some state via HomeKit and the FHEM adapter doesn‘t update the cache anymore. Closing HomeKit and opening it again shows the wrong (initially cached) state.

**Comment by justme-1968** [comment]
i have no idea how this would influence caching.

what do you see in the log if a new fhem event is received?

**Comment by emcepe** [comment]
I see the exact same behaviour with my installation.

**Comment by justme-1968** [comment]
sorry for the trouble. i think i have fixed it now.

**Comment by justme-1968** [comment]
had to revert this due to side effects. i will try to find a working version.

**Pull request merged**
